FROM ghcr.io/shiro160/prac/codespace:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        apache2 \
        php

USER root

WORKDIR /var/www/html/
CMD ["apachectl", "-D", "FOREGROUND"]